language: java
jdk:
  - openjdk8

branches:
  only:
    - step4

# Travis CI 서버의 Home
caches:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r jwp-blog *
  - mkdir -p deploy
  - mv jwp-blog.zip deploy/jwp-blog.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jwp-blog
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: step4

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: jwp-blog
    key: jwp-blog.zip
    bundle_type: zip
    application: jwp-blog
    deployment_group: jwp-blog-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: step4

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dpudpu11@gmail.com
