language: java
jdk:
  - openjdk8

branches:
  only:
    - step4

# Travis CI 서버의 Home
caches:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dpudpu11@gmail.com

